### ISSUE TITLE
KeyError: 'HTTP_REFERER'

### ISSUE THREAD

**Issue by eriktelepovsky** [yunojuno/django-package-monitor#3]
``/package_monitor/views.py`` in ``reload``:

```
Traceback (most recent call last):
  File "/Users/erik/env/cargo/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/erik/env/cargo/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/erik/env/cargo/lib/python2.7/site-packages/package_monitor/views.py", line 14, in reload
    url = request.META['HTTP_REFERER']
KeyError: 'HTTP_REFERER'
```

**Comment by hugorodgerbrown** [comment]
Hi Erik - I appreciate this may not be possible, but is your Django project code available?

**Comment by eriktelepovsky** [comment]
Hi, no it's not. But you can simulate this error very easily. Just type ``http://127.0.0.1:8000/package_monitor/reload/`` in your browser.

**Comment by hugorodgerbrown** [comment]
I've fixed this by simply returning a 200 and a confirmation message (so you could call the URL direct if you needed to).
